apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  replicas: 1
  serviceName: consul
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:1.9.9
        ports:
        - containerPort: 8500
          name: http
        - containerPort: 8600
          name: DNS