apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-txt-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /backend/mysqlConnectorInstances.txt





