apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: main-app-container
          image: zizoufg/main-app:v1.0
          