apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-connector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-connector
  template:
    metadata:
      labels:
        app: mysql-connector
    spec:
      containers:
        - name: mysql-connector
          image: zizoufg/mysql-connector:v1.0
          ports:
            - containerPort: 3000
        