apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: service-creator
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "update", "delete", "list", "watch"]
